version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: yourusername
      DATABASE_PASSWORD: yourpassword
      DATABASE_NAME: leaderboard
    ports:
      - "3000:3000"
    volumes:
      - .:/app
